### PR TITLE
Remove page index check to allow lazy-loading dictionary pages

### LINKED ISSUE #219: panic in `Read` after seeking to random row
Ok so it appears that in _some cases_ seeking to a random row and reading results in a panic. I've downloaded a block from our dev environment and hard-coded a search for a specific traceID in the following test to replicate the panic (could not find a minimal test case to reproduce the bug)

```golang
func TestBackendBlockFindTraceByID_TestData(t *testing.T) {
	rawR, _, _, err := local.New(&local.Config{
		Path: "./test-data",
	})
	require.NoError(t, err)

	r := backend.NewReader(rawR)
	ctx := context.Background()

	blocks, err := r.Blocks(ctx, "vulture-tenant")
	require.NoError(t, err)
	assert.Len(t, blocks, 1)

	meta, err := r.BlockMeta(ctx, blocks[0], "vulture-tenant")
	require.NoError(t, err)

	b, err := NewBackendBlock(meta, r)
	require.NoError(t, err)

	bytes, _ := util.HexStringToTraceID("7d80fcd3e4978d6143030ef00d8bccc1")
	tr, err := b.FindTraceByID(ctx, bytes)
	require.NoError(t, err)

	require.NotNil(t, tr)
}

```
https://github.com/annanay25/tempo/blob/7a7e968e2a427f5e91890ac0eebbd47031539e9e/tempodb/encoding/vparquet/block_findtracebyid_test.go#L118

And this results in the following panic

```
        	Error Trace:	block_findtracebyid_test.go:139
        	Error:      	Received unexpected error:
        	            	decoding page 1 of column "Key": unexpected dictionary page
        	            	error reading row from backend
        	            	github.com/grafana/tempo/tempodb/encoding/vparquet.(*backendBlock).FindTraceByID
        	            		/Users/annanay/Desktop/git/go/src/github.com/grafana/tempo/tempodb/encoding/vparquet/block_findtracebyid.go:219
        	            	github.com/grafana/tempo/tempodb/encoding/vparquet.TestBackendBlockFindTraceByID_TestData
        	            		/Users/annanay/Desktop/git/go/src/github.com/grafana/tempo/tempodb/encoding/vparquet/block_findtracebyid_test.go:138
        	            	testing.tRunner
        	            		/usr/local/go/src/testing/testing.go:1259
        	            	runtime.goexit
        	            		/usr/local/go/src/runtime/asm_amd64.s:1581
        	Test:       	TestBackendBlockFindTraceByID_TestData
```

I did some digging and it seems to go away when the following lines are removed:
https://github.com/segmentio/parquet-go/blob/86cb68738df079b236e082d0ee49436b86981470/file.go#L544-L546
which makes sense because now we are reading dictionary pages lazily even if the page index is > 0? Just a preliminary hypothesis

### PR DESCRIPTION
**Pull request by annanay25**
Should fix #219 

Signed-off-by: Annanay Agarwal <annanay.agarwal@grafana.com>

### CODE REVIEW

File: file.go [hunk 1]
```diff
@@ -541,9 +541,6 @@ func (f *filePages) readDictionaryPage(header *format.PageHeader, page *dataPage
 	if header.DictionaryPageHeader == nil {
 		return ErrMissingPageHeader
 	}
-	if f.index > 0 {
-		return ErrUnexpectedDictionaryPage
-	}
```
Comment (annanay25) [inline file.go:546]: On second thought, the following appears to be an appropriate spot for the index check:
https://github.com/segmentio/parquet-go/blob/86cb68738df079b236e082d0ee49436b86981470/file.go#L482-L486

ie.. if we encounter a dictionary page beyond the first index while scanning, that should result in a `ErrUnexpectedDictionaryPage`. However, if we are lazy-loading a dictionary page from the top of the columnchunk, the index of the current page doesn't matter.

I'm not sure how I can come up with a test for this though, I can move the check to the new location if it looks ok to you?

**Comment by annanay25** [comment]
@achille-roussel ping on this one, just checking if you got a chance to review!

**Review by achille-roussel — APPROVED** [review]
The fix looks good, thanks for the contribution!
