### PR TITLE
fix issue 340

### LINKED ISSUE #340: Fix reading of file from parquet-testing/26
https://github.com/apache/parquet-testing/pull/26

### PR DESCRIPTION
**Pull request by achille-roussel**
Fixes #340 

See https://github.com/apache/parquet-testing/pull/26 for context.

### CODE REVIEW

File: column.go [hunk 1]
```diff
@@ -561,24 +561,39 @@ func (c *Column) decodeDataPageV2(header DataPageHeaderV2, page *buffer, dict Di
...
 
-	if c.maxRepetitionLevel > 0 {
-		encoding := lookupLevelEncoding(header.RepetitionLevelEncoding(), c.maxRepetitionLevel)
-		length := header.RepetitionLevelsByteLength()
-		repetitionLevels, pageData, err = decodeLevelsV2(encoding, numValues, pageData, length)
+	if length := header.RepetitionLevelsByteLength(); length > 0 {
+		if c.maxRepetitionLevel == 0 {
+			// In some cases we've observed files which have a non-zero
+			// repetition level despite the column not being repeated
+			// (nor nested within a repeated column).
```
Comment (kevinburkesegment) [inline column.go:568]: I would simply set the repetition level to 0 if the column is not repeated

**Review by kevinburkesegment — APPROVED** [review]

File: column.go (hunk 1 above)
Comment (achille-roussel) [reply column.go:568]: Do you mean modifying the header passed to the function to set `RepetitionLevelByteLength` to zero?

File: internal/debug/debug.go [hunk 2]
```diff
@@ -19,7 +20,7 @@ type ioReaderAt struct {
 
 func (d *ioReaderAt) ReadAt(b []byte, off int64) (int, error) {
 	n, err := d.reader.ReadAt(b, off)
-	fmt.Printf("%s: Read(%d) @%d => %d %v \n  %q\n", d.prefix, len(b), off, n, err, b[:n])
```
Comment (abraithwaite) [inline internal/debug/debug.go:22]: Neat, TIL of this package's existence!
