### PR TITLE
Fix Generic Read methods to read all rows up to length of argument

### LINKED ISSUE #469: [Bug] parquet.readFile only reads 1024 rows
This file (zipped parquet file):
[debug.zip](https://github.com/segmentio/parquet-go/files/10542463/debug.zip) has more than 1024 rows (around 9K).

But if I read it using the following code:

```
type RowType struct {
	Name string `parquet:",optional"`
	Data []byte `parquet:",optional"`
}

rows, err := parquet.ReadFile[RowType](file)
```

and print out the number of rows, I only see that there are 1024 rows.
Tools like the `pandas` library from Python don't have this issue.

### PR DESCRIPTION
**Pull request by bartleyg**
This fixes the generic Read methods where only one page worth of rows was read instead of all rows up to length of the argument slice. This affected at least `parquet.ReadFile`, `parquet.Read`, and `GenericReader.Read`.

You can see a failed test here https://github.com/segmentio/parquet-go/actions/runs/4515595007/jobs/7953065166 without the fix with a new test case using larger sizes here https://github.com/segmentio/parquet-go/pull/489/files#diff-306797de164c962fe5b992da67ab7ff245b8a8e7c76ca21e350ee08c7071d39eR494.

I added a new generic Read path test with multiple RowGroups & multiple Pages to increase the test coverage around this.

I also noted that the TestWriter writerTests have been skipped since using Github Actions because parquet-tools are not installed in Github CI.

Fixes #469, #471, & possibly others.

### CODE REVIEW

File: parquet_go18_test.go [hunk 1]
```diff
@@ -326,6 +326,72 @@ func TestIssue377(t *testing.T) {
...
+		}
+		// Flush writes rows as row group. 4 total (20k/5k) in this file.
+		if (i+1)%maxPageBytes == 0 {
+			err = w.Flush()
+			if err != nil {
+				t.Fatal("w.Flush: ", err)
+			}
+		}
+	}
+	err = w.Close()
```
Comment (kevinburkesegment) [inline parquet_go18_test.go:368]: Can shorten the test and also avoid shadowing this variable by doing e.g.

```go
if err := w.Close(); err != nil {
    t.Fatalf("w.Close: %v", err)

File: reader_go18.go [hunk 2]
```diff
@@ -127,24 +134,40 @@ func (r *GenericReader[T]) Close() error {
 	return r.base.Close()
 }
 
+// readRows reads the next rows from the reader into the given rows slice up to len(rows).
```
Comment (kevinburkesegment) [inline reader_go18.go:137]: > // readRows reads the next rows from the reader into the given rows slice up to len(rows).

How about 

> // readRows reads the next rows from the reader into r, up to len(rows).

File: parquet_go18_test.go (hunk 1 above)
Comment (bartleyg) [reply parquet_go18_test.go:368]: It's not shadowed. Doing the suggestion would shadow. I find the `if err := work(); err != nil {` pattern very unreadable just to save a line.
